In [42]:
import numpy as np

# Hàm đưa ma trận về dạng bậc thang

In [43]:
def Gauss_Elimination(A):
    A = A.astype(float)
    n = A.shape[0]
    
    for i in range(n):
        # Tìm hàng có giá trị lớn nhất trong cột đầu tiên chưa xử lý
        min_row = np.argmin(np.abs(A[i:, i])) + i
        # print('Min_row = ', min_row)
        
        # Hoán đổi hàng thứ i và hàng có giá trị lớn nhất
        # print('A[[i, min_row]] = ', A[[i, min_row]])
        # print('A[[min_row, i]] = ', A[[min_row, i]])
        A[[i, min_row]] = A[[min_row, i]]
        
        # Loại bỏ các phần tử bên dưới đường chéo chính
        for j in range(i + 1, n):
            ratio = A[j, i] / A[i, i]
            A[j, :] -= ratio * A[i, :]
    
    return A


# Rút gọn về dạng ma trận bậc thang rút gọn

In [44]:
def Reduce_Matrix(A):
    A = A.astype(float)
    n = A.shape[0]
    
    for i in range(n):
        min_row = np.argmin(np.abs(A[i:, i])) + i
        A[[i, min_row]] = A[[min_row, i]]
        
        pivot = A[i, i]
        A[i, :] /= pivot
        
        for j in range(i + 1, n):
            ratio = A[j, i] / A[i, i]
            A[j, :] -= ratio * A[i, :]
    
    for i in range(n - 1, 0, -1):
        for j in range(i - 1, -1, -1):
            ratio = A[j, i] / A[i, i]
            A[j, :] -= ratio * A[i, :]
    
    return A

# Hàm tìm nghiệm của hệ phương trình

In [46]:
def back_substitution(A):
    n = A.shape[0]
    #print('n = ', n)
    x = np.zeros(n)
    # print('x =', x)
    for i in range(n - 1, -1, -1):
        # print('i = ', i)
        # print('A[i, -1] = ', A[i, -1])
        # print('A[i, :-1] = ', A[i, :-1])
        # print('A[i, i] = ', A[i, i])
        # print('np.dot(A[i, :-1], x) = ', np.dot(A[i, :-1], x))
        x[i] = (A[i, -1] - np.dot(A[i, :-1], x)) / A[i, i]
    
    return x


In [48]:
# Tạo ma trận mở rộng A
A = np.array([[1, 2, -1, -1],
              [2, 2, 1, 1],
              [3, 5, -2, -1]])

# Áp dụng Gauss-Elimination để tìm ma trận bậc thang
A_reduced = Gauss_Elimination(A)

A_reduced_form = Reduce_Matrix(A)

# Áp dụng back substitution để tìm nghiệm của hệ phương trình
solution = back_substitution(A_reduced)

print("Ma trận ban đầu: ")
print(A)
print("Ma trận bậc thang:")
print(A_reduced)
print("Ma trận bậc thang rút gọn:")
print(A_reduced_form)
print("Nghiệm của hệ phương trình:")
print(solution)

Ma trận ban đầu: 
[[ 1  2 -1 -1]
 [ 2  2  1  1]
 [ 3  5 -2 -1]]
Ma trận bậc thang:
[[ 1.  2. -1. -1.]
 [ 0. -1.  1.  2.]
 [ 0.  0.  1. -1.]]
Ma trận bậc thang rút gọn:
[[ 1.  0.  0.  4.]
 [ 0.  1.  0. -3.]
 [ 0.  0.  1. -1.]]
Nghiệm của hệ phương trình:
[ 4. -3. -1.]
